#!/bin/bash

cd $HOME
git clone https://github.com/spookypeanut/configfiles.git
mkdir -p bin
for i in .bashrc .ripit .vimrc .vim .inputrc .profile .screenrc todo.cfg .tmux.conf .Xmodmap; do
    ln -s configfiles/$i .
done

for i in whipper MusicBrainz; do
    ln -s configfiles/$i .config/

mkdir -p ~/.ipython
ln -s configfiles/ipythonrc .ipython/

echo "Now copy across the .bashrc.fscfc if necessary"
echo "And choose which .gitconfig to use"
