#!/bin/bash

http_proxy=proxy.framestore.com:8001
https_proxy=proxy.framestore.com:8001

cd $HOME
git clone https://github.com/spookypeanut/configfiles.git
mkdir -p bin
for i in .bashrc .vimrc .vim .inputrc .profile .screenrc todo.cfg .tmux.conf; do
    ln -s configfiles/$i .
done

for i in vimman; do
    ln -s configfiles/$i ./bin/
done

mkdir -p ~/.ipython
ln -s configfiles/ipythonrc .ipython/

echo "Now copy across the .bashrc.fscfc if necessary"
echo "And choose which .gitconfig to use"
